In [1]:
import torch.functional as F
import torch
from torch.nn import functional as F

In [2]:
# Attention demo code
def attention(q,k,v):
    # q, k, v shape: (batch_size, seq_len, dim)
    score = q @ k.transpose(1,2)
    score = score / (k.size(-1) ** 0.5)
    score = F.softmax(score, dim=-1)
    output = score @ v
    return output

In [5]:
batch_size = 1
seq_len = 2
dim = 4

q = torch.randn(batch_size, seq_len, dim)
k = torch.randn(batch_size, seq_len, dim)
v = torch.randn(batch_size, seq_len, dim)

output = attention(q, k, v)

print(output)

tensor([[[ 0.2059, -0.2209,  0.5415, -0.5711],
         [ 0.3654, -0.1495,  0.6590, -0.4663]]])


In [6]:
def test_attention():
    batch_size = 1
    seq_len = 5
    dim = 4

    q = torch.randn(batch_size, seq_len, dim)
    k = torch.randn(batch_size, seq_len, dim)
    v = torch.randn(batch_size, seq_len, dim)

    output = attention(q,k,v)

    print(output)

    output2 = F.scaled_dot_product_attention(q,k,v,is_causal=False)

    print(output2)

    assert torch.allclose(output, output2)

test_attention()
    

tensor([[[-0.2881, -0.8231,  0.8004,  1.0026],
         [ 1.4148, -1.4936,  0.3784,  0.7028],
         [-0.9982, -1.0546,  1.0988,  1.5405],
         [ 2.0777, -1.8968,  0.2108,  0.9061],
         [-0.5247, -0.0417,  1.2336,  0.1887]]])
tensor([[[-0.2881, -0.8231,  0.8004,  1.0026],
         [ 1.4148, -1.4936,  0.3784,  0.7028],
         [-0.9982, -1.0546,  1.0988,  1.5405],
         [ 2.0777, -1.8968,  0.2108,  0.9061],
         [-0.5247, -0.0417,  1.2336,  0.1887]]])
